<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Gs_divisionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $gs_devision = [
    ['name' => 'Colombo'],
    ['name' => 'Dehiwala-Mount Lavinia'],
    ['name' => 'Hanwella'],
    ['name' => 'Homagama'],
    ['name' => 'Kaduwela'],
    ['name' => 'Kesbewa'],
    ['name' => 'Kolonnawa'],
    ['name' => 'Maharagama'],
    ['name' => 'Moratuwa'],
    ['name' => 'Padukka'],
    ['name' => 'Ratmalana'],
    ['name' => 'Sri Jayawardanapura Kotte'],
    ['name' => 'Thimbirigasyaya'],

    ['name' => 'Attanagalla'],
    ['name' => 'Biyagama'],
    ['name' => 'Divulapitiya'],
    ['name' => 'Dompe'],
    ['name' => 'Gampaha'],
    ['name' => 'Ja-ela'],
    ['name' => 'Katana'],
    ['name' => 'Kelaniya'],
    ['name' => 'Mahara'],
    ['name' => 'Minuwangoda'],
    ['name' => 'Mirigama'],
    ['name' => 'Negombo'],
    ['name' => 'Wattala'],

    ['name' => 'Agalawatta'],
    ['name' => 'Bandaragama'],
    ['name' => 'Beruwala'],
    ['name' => 'Bulathsinhala'],
    ['name' => 'Dodangoda'],
    ['name' => 'Horana'],
    ['name' => 'Ingiriya'],
    ['name' => 'Kalutara'],
    ['name' => 'Madurawela'],
    ['name' => 'Matugama'],
    ['name' => 'Millaniya'],
    ['name' => 'Palindanuwara'],
    ['name' => 'Panadura'],
    ['name' => 'Walallawita'],

    ['name' => 'Akurana'],
    ['name' => 'Deltota'],
    ['name' => 'Dolduwa'],
    ['name' => 'Ganga Ihala Korale'],
    ['name' => 'Harispattuwa'],
    ['name' => 'Hatharaliyadda'],
    ['name' => 'Kandy Four Gravets & Gangawata Korale'],
    ['name' => 'Kundasale'],
    ['name' => 'Medadumbara'],
    ['name' => 'Minipe'],
    ['name' => 'Panvila'],
    ['name' => 'Pasbage Korale'],
    ['name' => 'Pathadumbara'],
    ['name' => 'Pathahewaheta'],
    ['name' => 'Poojapitiya'],
    ['name' => 'Thumpane'],
    ['name' => 'Udadumbara'],
    ['name' => 'Udapalatha'],
    ['name' => 'Udunuwara'],
    ['name' => 'Yatinuwara'],

    ['name' => 'Ambanganga Korale'],
    ['name' => 'Dambulla'],
    ['name' => 'Galewela'],
    ['name' => 'Laggala-Pallegama'],
    ['name' => 'Matale'],
    ['name' => 'Naula'],
    ['name' => 'Pallepola'],
    ['name' => 'Rattota'],
    ['name' => 'Ukuwela'],
    ['name' => 'Wilgamuwa'],
    ['name' => 'Yatawatta'],

    ['name' => 'Ambagamuwa'],
    ['name' => 'Hanguranketha'],
    ['name' => 'Kothmale'],
    ['name' => 'Mathurata'],
    ['name' => 'Nildandah'],
    ['name' => 'Norwood'],
    ['name' => 'Nuwara Eliya'],
    ['name' => 'Thalawakale'],
    ['name' => 'Walapane'],

    ['name' => 'Akmeemana'],
    ['name' => 'Ambalangoda'],
    ['name' => 'Baddegama'],
    ['name' => 'Balapitiya'],
    ['name' => 'Bentota'],
    ['name' => 'Bope-Poddala'],
    ['name' => 'Elpitiya'],
    ['name' => 'Galle Four Gravets'],
    ['name' => 'Gonapinuwala'],
    ['name' => 'Habaraduwa'],
    ['name' => 'Hikkaduwa'],
    ['name' => 'Imaduwa'],
    ['name' => 'Karandeniya'],
    ['name' => 'Madampagama'],
    ['name' => 'Nagoda'],
    ['name' => 'Neluwa'],
    ['name' => 'Niyagama'],
    ['name' => 'Waduramba'],
    ['name' => 'Welivitiya-Divithura'],
    ['name' => 'Thawalama'],
    ['name' => 'Yakkalamulla'],

    ['name' => 'Akuressa'],
    ['name' => 'Athuraliya'],
    ['name' => 'Devinuwara'],
    ['name' => 'Dickwella'],
    ['name' => 'Four Gravets'],
    ['name' => 'Hakmana'],
    ['name' => 'Kamburupitiya'],
    ['name' => 'Kirinda Puhulwella'],
    ['name' => 'Kotapola'],
    ['name' => 'Malimbada'],
    ['name' => 'Mulatiyana'],
    ['name' => 'Pasgoda'],
    ['name' => 'Pitabeddara'],
    ['name' => 'Thihagoda'],
    ['name' => 'Weligama'],
    ['name' => 'Welipitiya'],

    ['name' => 'Hambantota'],
    ['name' => 'Ambalantota'],
    ['name' => 'Angunakolapelassa'],
    ['name' => 'Beliatta'],
    ['name' => 'Weeraketiya'],
    ['name' => 'Katuwana'],
    ['name' => 'Lunugamvehera'],
    ['name' => 'Okewala'],
    ['name' => 'Sooriyawewa'],
    ['name' => 'Tangalle'],
    ['name' => 'Tissamaharama'],
    ['name' => 'Walasmulla'],

    ['name' => 'Delft'],
    ['name' => 'Island North (Kayts)'],
    ['name' => 'Island South ,Velanai'],
    ['name' => 'Jaffna'],
    ['name' => 'Karainagar'],
    ['name' => 'Nallur'],
    ['name' => 'Thenmaradchi (Chavakachcheri)'],
    ['name' => 'Vadamaradchi East (Maruthnkerny)'],
    ['name' => 'Vadamaradchi North (Point Pedro)'],
    ['name' => 'Vadamaradchy South-West, Karaveddy'],
    ['name' => 'Valikamam North (Tellipallai)'],
    ['name' => 'Valikamam South (Uduvil)'],
    ['name' => 'Valikamam South-West (Sandilipay)'],
    ['name' => 'Valikamam West (Chankanai)'],
    ['name' => 'Valikamam-East(kopayi)'],

    ['name' => 'Madhu'],
    ['name' => 'Mannar Town'],
    ['name' => 'Manthai West'],
    ['name' => 'Musali'],
    ['name' => 'Nanaddan'],

    ['name' => 'Kandavalai'],
    ['name' => 'Karachchi'],
    ['name' => 'Pachchilaipalli'],
    ['name' => 'Poonakary'],

    ['name' => 'Manthai East'],
    ['name' => 'Maritimepattu'],
    ['name' => 'Oddusadan'],
    ['name' => 'Puthukudiyiruppu'],
    ['name' => 'Thunukkai'],
    ['name' => 'Welioya'],

    ['name' => 'Vavuniya'],
    ['name' => 'Vavuniya North'],
    ['name' => 'Vavuniya South'],
    ['name' => 'Vengalacheddikulam'],

    ['name' => 'Seruvila'],
    ['name' => 'Kantalai'],
    ['name' => 'Morawewa'],
    ['name' => 'Gomarankadawala'],
    ['name' => 'Trincomalee'],
    ['name' => 'Kuchchaveli'],
    ['name' => 'Thampalakamam'],
    ['name' => 'Muttur'],
    ['name' => 'Kinniya'],
    ['name' => 'Padavi Sri Pura'],
    ['name' => 'Verugal'],

    ['name' => 'Eravur'],
    ['name' => 'Eravur Town'],
    ['name' => 'Kattankudy'],
    ['name' => 'Koralaipattu'],
    ['name' => 'Koralaipattu West'],
    ['name' => 'Koralaipattu North'],
    ['name' => 'Koralaipattu Central'],
    ['name' => 'Koralaipattu South'],
    ['name' => 'Manmunai North'],
    ['name' => 'Manmunai Pattu'],
    ['name' => 'Manmunai S. and Eruvil Pattu'],
    ['name' => 'Manmunai South West'],
    ['name' => 'Manmunai West'],
    ['name' => 'Porativu Pattu'],

    ['name' => 'Addalachchenai'],
    ['name' => 'Akkaraipattu'],
    ['name' => 'Alayadiwembu'],
    ['name' => 'Ampara'],
    ['name' => 'Dehiyattakandiya'],
    ['name' => 'Damana'],
    ['name' => 'Eragama'],
    ['name' => 'Kallmunai Muslim'],
    ['name' => 'Kallmunai Tamil'],
    ['name' => 'Karaithivu'],
    ['name' => 'Mahaoya'],
    ['name' => 'Padiyatalawa'],
    ['name' => 'Sammanthurai'],
    ['name' => 'Saindamarathu'],
    ['name' => 'Potuvil'],
    ['name' => 'Lahugala'],
    ['name' => 'Nindavur'],
    ['name' => 'Thirukkovil'],
    ['name' => 'Navithanveli'],
    ['name' => 'Uhana'],

    ['name' => 'Alawwa'],
    ['name' => 'Ambanpola'],
    ['name' => 'Bingiriya'],
    ['name' => 'Ehatuwewa'],
    ['name' => 'Ganewatte'],
    ['name' => 'Galgamuwa'],
    ['name' => 'Giribawa'],
    ['name' => 'Ibbagamuwa'],
    ['name' => 'Kotawehara'],
    ['name' => 'Kobeigane'],
    ['name' => 'Kuliyapitiya'],
    ['name' => 'Kurunegala'],
    ['name' => 'Maho'],
    ['name' => 'Maspotha'],
    ['name' => 'Mallawapitiya'],
    ['name' => 'Mawathagama'],
    ['name' => 'Narammala'],
    ['name' => 'Nikaweratiya'],
    ['name' => 'Panduwasnuwara East'],
    ['name' => 'Panduwasnuwara West'],
    ['name' => 'Pannala'],
    ['name' => 'Polgahawela'],
    ['name' => 'Polpithigama'],
    ['name' => 'Rasnayakapure'],
    ['name' => 'Rideegama'],
    ['name' => 'Weerabugedara'],
    ['name' => 'Wariyapola'],
    ['name' => 'Udubaddawa'],

    ['name' => 'Puttalam'],
    ['name' => 'Dankotuwa'],
    ['name' => 'Chilaw'],
    ['name' => 'Anamaduwa'],
    ['name' => 'Arachchikattuwa'],
    ['name' => 'Kalpitiya'],
    ['name' => 'Karuwalagaswewa'],
    ['name' => 'Mahakumbukkamkadawala'],
    ['name' => 'Madampe'],
    ['name' => 'Mahawewa'],
    ['name' => 'Mundel'],
    ['name' => 'Nattandiya'],
    ['name' => 'Nawagattegama'],
    ['name' => 'Pallama'],
    ['name' => 'Wanathawilluwa'],
    ['name' => 'Wennappuwa'],

    ['name' => 'Galnewa'],
    ['name' => 'Galenbindunuwewa'],
    ['name' => 'Horowpathana'],
    ['name' => 'Ipalogama'],
    ['name' => 'Kahatagasdigiliya'],
    ['name' => 'Kebathigollawa'],
    ['name' => 'Kekirawa'],
    ['name' => 'Mahawillachchiya'],
    ['name' => 'Medawachchciya'],
    ['name' => 'Mihintale'],
    ['name' => 'Nachchadoowa'],
    ['name' => 'Nochchiyagama'],
    ['name' => 'Nuwaragam Palatha (East)'],
    ['name' => 'Nuwaragam Palatha (Central)'],
    ['name' => 'Padaviya'],
    ['name' => 'Palagala'],
    ['name' => 'Palugaswewa'],
    ['name' => 'Rajanganaya'],
    ['name' => 'Rambewa'],
    ['name' => 'Thalawa'],
    ['name' => 'Thabuththegama'],
    ['name' => 'Thirappane'],

    ['name' => 'Dimbulagala'],
    ['name' => 'Elahera'],
    ['name' => 'Hingurakgoda'],
    ['name' => 'Lankapura'],
    ['name' => 'Medirigiriyaa'],
    ['name' => 'Thamankaduwas'],
    ['name' => 'Welikanda'],

    ['name' => 'Bandarawela'],
    ['name' => 'Badulla'],
    ['name' => 'Ella'],
    ['name' => 'Haldummulla'],
    ['name' => 'Hali-Ela'],
    ['name' => 'Haputale'],
    ['name' => 'Kandeketiya'],
    ['name' => 'Lunugala'],
    ['name' => 'Mahiyanganaya'],
    ['name' => 'Meegahakiula'],
    ['name' => 'Passara'],
    ['name' => 'Rideemaliyadda'],
    ['name' => 'Soranatota'],
    ['name' => 'Uva Paranagama'],
    ['name' => 'Welimada'],

    ['name' => 'Badalkumbara'],
    ['name' => 'Bibila'],
    ['name' => 'Buttala'],
    ['name' => 'Kataragama'],
    ['name' => 'Madulla'],
    ['name' => 'Medagama'],
    ['name' => 'Moneragala'],
    ['name' => 'Sewanagala'],
    ['name' => 'Siyambalanduwa'],
    ['name' => 'Thanamalwila'],
    ['name' => 'Wellawaya'],

    ['name' => 'Ayagama'],
    ['name' => 'Balangoda'],
    ['name' => 'Eheliyagoda'],
    ['name' => 'Elapattha'],
    ['name' => 'Embilipitiya'],
    ['name' => 'Godakawela'],
    ['name' => 'Imbulpe'],
    ['name' => 'Kahawatta'],
    ['name' => 'Kalawana'],
    ['name' => 'iriella'],
    ['name' => 'Kolonna'],
    ['name' => 'Kuruvita'],
    ['name' => 'Nivithigala'],
    ['name' => 'Opanayaka'],
    ['name' => 'Pelmadulla'],
    ['name' => 'Ratnapura'],
    ['name' => 'Weligepola'],

    ['name' => 'Aranayaka'],
    ['name' => 'Bulathkohupitiya'],
    ['name' => 'Dehiowita'],
    ['name' => 'Deraniyagala'],
    ['name' => 'Galigamuwa'],
    ['name' => 'Kegalle'],
    ['name' => 'Mawanella'],
    ['name' => 'ambukkana'],
    ['name' => 'Ruwanwella'],
    ['name' => 'Warakapola'],
    ['name' => 'Yatiyanthota'],
];

 DB::table('gs_divisions')->insertOrIgnore($gs_devision);

    }
}