<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PoliceStationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         $police = [

            // Western Province
            //Colombo
            ['name' => 'Pettah'],
            ['name' => 'Keselwatta'],
            ['name' => 'Woulfendhal'],
            ['name' => 'Dam Street'],
            ['name' => 'Fort'],
            ['name' => 'Slave Island'],
            ['name' => 'Maradana'],
            ['name' => 'Maligawatta'],
            ['name' => 'Kotahena'],
            ['name' => 'Modara'],
            ['name' => 'Grandpass'],
            ['name' => 'Dematagoda'],
            ['name' => 'Mattakkuliya'],
            ['name' => 'Forshore'],
            ['name' => 'Bloemendhal'],
            ['name' => 'Armour Street'],

            // Gampaha
            ['name' => 'Gampaha'],
            ['name' => 'Minuwangoda'],
            ['name' => 'Kiridiwela'],
            ['name' => 'Dompe'],
            ['name' => 'Weeragula'],
            ['name' => 'Ganemulla'],
            ['name' => 'Welivariya'],
            ['name' => 'Nittambuwa'],
            ['name' => 'Meerigama'],
            ['name' => 'Weeyangoda'],
            ['name' => 'Peliyagoda'],
            ['name' => 'Kadana'],
            ['name' => 'Ja-Ela'],
            ['name' => 'Ragama'],
            ['name' => 'Negombo'],
            ['name' => 'Divulapitiya'],
            ['name' => 'Pamunugama'],
            ['name' => 'Kotadeniyawa'],
            ['name' => 'Katunayaka'],
            ['name' => 'Seeduwa'],
            ['name' => 'Kochchikade'],
            ['name' => 'Raddolugama'],
            ['name' => 'Biyagama'],
            ['name' => 'Meegahawatta'],
            ['name' => 'Sapugaskanda'],
            ['name' => 'Mahara'],
            ['name' => 'Ekala'],
            ['name' => 'Welisara'],
            ['name' => 'Kiribathgoda'],
            ['name' => 'Kadawatha'],
            ['name' => 'Pugoda'],
            ['name' => 'Kelaniya'],
            ['name' => 'Negombo'],

            //Kalutara
            ['name' => 'Panadura South'],
            ['name' => 'Panadura North'],
            ['name' => 'Wadduwa'],
            ['name' => 'Bandaragama'],
            ['name' => 'Anguruwatota'],
            ['name' => 'Millaniya'],
            ['name' => 'Horana'],
            ['name' => 'Ingiriya'],
            ['name' => 'Moragahahena'],
            ['name' => 'Moronthuduwa'],
            ['name' => 'Kalutara South'],
            ['name' => 'Kalutara North'],
            ['name' => 'Payagala'],
            ['name' => 'Dodangoda'],
            ['name' => 'Aluthgama'],
            ['name' => 'Welipanna'],
            ['name' => 'Beruwala'],
            ['name' => 'Mathugama'],
            ['name' => 'Bulathsinhala'],
            ['name' => 'Thebuwana'],
            ['name' => 'Baduraliya'],
            ['name' => 'Meegahathenna'],
            ['name' => 'Thiniyawala'],

            // Central Province
            ['name' => 'Alawathugoda'],
            ['name' => 'Ankumbura'],
            ['name' => 'Balangoda'],
            ['name' => 'Dalada Maligawa'],
            ['name' => 'Daulagala'],
            ['name' => 'Galagedara'],
            ['name' => 'Hanguranketha'],
            ['name' => 'Hasalaka'],
            ['name' => 'Hatharaliyadda'],
            ['name' => 'Kadugannawa'],
            ['name' => 'Kandy'],
            ['name' => 'Katugasthota'],
            ['name' => 'Menikhinna'],
            ['name' => 'Panwila'],
            ['name' => 'Peradeniya'],
            ['name' => 'Rangala'],
            ['name' => 'Teldeniya'],
            ['name' => 'Thalatuoya'],
            ['name' => 'Udadumbara'],
            ['name' => 'Wattegama'],

            //  Mullativu
            ['name' => 'Mankulam'],
            ['name' => 'Mullativu'],
            ['name' => 'Pudukuduiruppu'],
            ['name' => 'Muliyaweli'],
            ['name' => 'Oddusudan'],
            ['name' => 'Welioya'],
            ['name' => 'Mallavi'],

            // Nuwara Eliya
            ['name' => 'Ginigathhena'],
            ['name' => 'Norton Bridge'],
            ['name' => 'Watawala'],
            ['name' => 'Hatton'],
            ['name' => 'Maskeliya'],
            ['name' => 'Bogawanthalawa'],
            ['name' => 'Nallathanniya'],
            ['name' => 'Norwood'],
            ['name' => 'Nuwara Eliya'],
            ['name' => 'Nanuoya'],
            ['name' => 'Kandapola'],
            ['name' => 'Thalawakale'],
            ['name' => 'Agarapathana'],
            ['name' => 'Lindula'],
            ['name' => 'Dimbulapathana'],
            ['name' => 'Dayagama'],

        // Southern Province
            // Galle District
            ['name' => 'Galle'],
            ['name' => 'Ratgama'],
            ['name' => 'Hikkaduwa'],
            ['name' => 'Akmeemana'],
            ['name' => 'Wanduramba'],
            ['name' => 'Yakkalamulla'],
            ['name' => 'Poddala'],
            ['name' => 'Habaraduwa'],
            ['name' => 'Ahangama'],
            ['name' => 'Galle Harbour'],
            ['name' => 'Nagoda'],
            ['name' => 'Hiniduma'],
            ['name' => 'Neluwa'],
            ['name' => 'Udugama'],
            ['name' => 'Elpitiya'],
            ['name' => 'Uragasmanhandiya'],
            ['name' => 'Pitigala'],
            ['name' => 'Karandeniya'],
            ['name' => 'Baddegama'],
            ['name' => 'Meetiyagoda'],
            ['name' => 'Thelikada'],
            ['name' => 'Ambalangoda'],
            ['name' => 'Ahungalla'],
            ['name' => 'Kosgoda'],
            ['name' => 'Bentota'],

            // Matara
            ['name' => 'Matara'],
            ['name' => 'Gandara'],
            ['name' => 'Dikwella'],
            ['name' => 'Thihagoda'],
            ['name' => 'Kamburupitiya'],
            ['name' => 'Hakmana'],
            ['name' => 'Morawaka'],
            ['name' => 'Urubokka'],
            ['name' => 'Mawarala'],
            ['name' => 'Deniyaya'],
            ['name' => 'Weligama'],
            ['name' => 'Akuressa'],
            ['name' => 'Kananke'],
            ['name' => 'Pitabeddara'],
            ['name' => 'Kotawila'],
            ['name' => 'Kosmodara'],
            ['name' => 'Malimbada'],
            ['name' => 'Rotumba'],
            ['name' => 'Deyyandara'],

            // Hambantota
            ['name' => 'Tangalle'],
            ['name' => 'Hungama'],
            ['name' => 'Weeraketiya'],
            ['name' => 'Angunakolapelessa'],
            ['name' => 'Walasmulla'],
            ['name' => 'Beliatta'],
            ['name' => 'Katuwana'],
            ['name' => 'Middeniya'],
            ['name' => 'Sooriyawewa'],
            ['name' => 'Hambantota'],
            ['name' => 'Ambalantota'],
            ['name' => 'Tissamaharamaya'],
            ['name' => 'Kataragama'],
            ['name' => 'Lunugamwehera'],
            ['name' => 'Weeravila'],

        // Northern Province
            // Jaffna
            ['name' => 'Kankesanthurai'],
            ['name' => 'Achchuveli'],
            ['name' => 'Ilavalai'],
            ['name' => 'Palali'],
            ['name' => 'Tellipalai'],
            ['name' => 'Point Pedro'],
            ['name' => 'Nelliadi'],
            ['name' => 'Velvetithurai'],
            ['name' => 'Jaffna'],
            ['name' => 'Manipay'],
            ['name' => 'Chunnakam'],
            ['name' => 'Chavakachcheri'],
            ['name' => 'Kopay'],
            ['name' => 'Kodikamam'],
            ['name' => 'Kayts'],
            ['name' => 'Delft'],
            ['name' => 'Vaddukoddai'],

            // Kilinochchi
            ['name' => 'Kilinochchi'],
            ['name' => 'Head Quarter Inspector'],
            ['name' => 'Poonakary'],
            ['name' => 'Palai'],
            ['name' => 'Mulankavil'],
            ['name' => 'Naachchikkuda'],
            ['name' => 'Tharmapuram'],
            ['name' => 'Ramanathapuram'],
            ['name' => 'Akkarayankulam'],

            // Mannar
            ['name' => 'Mannar'],
            ['name' => 'Silawathura'],
            ['name' => 'Iluppakadawai'],
            ['name' => 'Wedithalathiu'],
            ['name' => 'Thalaimannar'],
            ['name' => 'Murunkan'],
            ['name' => 'Madu'],
            ['name' => 'Wankala'],
            ['name' => 'Pesale'],

            ['name' => 'Mankulam'],
            ['name' => 'Mullativu'],
            ['name' => 'Pudukuduiruppu'],
            ['name' => 'Muliyaweli'],
            ['name' => 'Oddusudan'],
            ['name' => 'Welioya'],
            ['name' => 'Mallavi'],

            //Vavuniya
            ['name' => 'Kanagarayankulam'],
            ['name' => 'Vavuniya'],
            ['name' => 'Irattaperiyakulam'],
            ['name' => 'Nedumkenrni'],
            ['name' => 'Chettikulam'],
            ['name' => 'Omantha'],
            ['name' => 'Puliyankulam'],
            ['name' => 'Parayanakulam'],
            ['name' => 'Ulukkulam'],
            ['name' => 'Ma-Maduwa'],
            ['name' => 'Puwarasamkulam'],
            ['name' => 'Echchanmkulam'],
            ['name' => 'Bogaswewa'],

            // Eastern Province
            // Trincomalee
            ['name' => 'Trincomalee'],
            ['name' => 'Trinco Harbour'],
            ['name' => 'Chinabay'],
            ['name' => 'Kuchchaweli'],
            ['name' => 'Uppuweli'],
            ['name' => 'Pulmudai'],
            ['name' => 'Sripura'],
            ['name' => 'Nilawely'],
            ['name' => 'Mutur'],
            ['name' => 'Sampoor'],
            ['name' => 'Kinnia'],
            ['name' => 'Kinnia'],
            ['name' => 'Kantale'],
            ['name' => 'Agbopura'],
            ['name' => 'Thambalagamuva'],
            ['name' => 'Serunuwara'],
            ['name' => 'Suriyapura'],
            ['name' => 'Wan Ela'],
            ['name' => 'Morawewa'],
            ['name' => 'Gomarankadawala'],

            // Batticaloa
            ['name' => 'Batticaloa'],
            ['name' => 'Vavunathive'],
            ['name' => 'Kaththankudi'],
            ['name' => 'Eravur'],
            ['name' => 'Karadiyanaru'],
            ['name' => 'Aiththamalai'],
            ['name' => 'Valachchanai'],
            ['name' => 'Kalkudah'],
            ['name' => 'Wakarai'],
            ['name' => 'Kalawanchikudy'],
            ['name' => 'Vellavali'],
            ['name' => 'Kokkadicholai'],

            // Ampara
            ['name' => 'Ampara'],
            ['name' => 'Damana'],
            ['name' => 'Inginiyagala'],
            ['name' => 'Uhana'],
            ['name' => 'Bakkiella'],
            ['name' => 'Central Camp'],
            ['name' => 'Mangalagama'],
            ['name' => 'Mahaoya'],
            ['name' => 'Dehiaththakandiya'],
            ['name' => 'Padiyathalawa'],
            ['name' => 'Kalmunai'],
            ['name' => 'Samanthurai'],
            ['name' => 'Chawalakade'],
            ['name' => 'Akkaraipattu'],
            ['name' => 'Thirukkovil'],
            ['name' => 'Pothuvil'],
            ['name' => 'Panama'],

            // North Western Province
            // Kurunegala
            ['name' => 'Kurunegala'],
            ['name' => 'Polgahawela'],
            ['name' => 'Alawwa'],
            ['name' => 'Pothuhera'],
            ['name' => 'Wariyapola'],
            ['name' => 'Weerambugedara'],
            ['name' => 'Wellawa'],
            ['name' => 'Gokarella'],
            ['name' => 'Mawathagama'],
            ['name' => 'Rideegama'],
            ['name' => 'Kumbukgatey'],
            ['name' => 'Kuliyapitiya'],
            ['name' => 'Narammala'],
            ['name' => 'Pannala'],
            ['name' => 'Giriulla'],
            ['name' => 'Hettipola'],
            ['name' => 'Katupotha'],
            ['name' => 'Dummalasooriya'],
            ['name' => 'Bingiriya'],
            ['name' => 'Nikaweratiya'],
            ['name' => 'Kobeigane'],
            ['name' => 'Kotawehera'],
            ['name' => 'Rasnayakapura'],
            ['name' => 'Maho'],
            ['name' => 'Ambanpola'],
            ['name' => 'Polpithigama'],
            ['name' => 'Galgamuwa'],
            ['name' => 'Meegalewa'],
            ['name' => 'Giribawa'],

            // Puttalam
            ['name' => 'Puttalam'],
            ['name' => 'Anamaduwa'],
            ['name' => 'Pallama'],
            ['name' => 'Nawagaththegama'],
            ['name' => 'Wanathawilluwa'],
            ['name' => 'Karuwalagaswewa'],
            ['name' => 'Saliyawewa'],
            ['name' => 'Kalpitiya'],
            ['name' => 'Mundal'],
            ['name' => 'Norochcholey'],
            ['name' => 'Udappuwa'],
            ['name' => 'Chilaw'],
            ['name' => 'Madampe'],
            ['name' => 'Marawila'],
            ['name' => 'Koswatta'],
            ['name' => 'Wennappuwa'],
            ['name' => 'Dankotuwa'],
            ['name' => 'Arachchikattuwa'],

            // North Central Province
            // Anuradapura
            ['name' => 'Anuradapura'],
            ['name' => 'Hidogama'],
            ['name' => 'Udamaluwa'],
            ['name' => 'Mihintale'],
            ['name' => 'Kekirawa'],
            ['name' => 'Thirappone'],
            ['name' => 'Eppawala'],
            ['name' => 'Galnewa'],
            ['name' => 'Galkiriyagama'],
            ['name' => 'Kebithigollawa'],
            ['name' => 'Medawachchiya'],
            ['name' => 'Padaviya'],
            ['name' => 'Thambuttegama'],
            ['name' => 'Rajanganaya'],
            ['name' => 'Nochchiyagama'],
            ['name' => 'Thalawa'],
            ['name' => 'Horowpathana'],
            ['name' => 'Kahatagasdigiliya'],
            ['name' => 'Thanthirimalaya'],
            ['name' => 'Mahawilachchiya'],
            ['name' => 'Galenbidunuwewa'],
            ['name' => 'Ipalogama'],
            ['name' => 'Parasangaswewa'],
            ['name' => 'Moragoda'],

            // Polonnaruwa
            ['name' => 'Polonnaruwa'],
            ['name' => 'Pulasthipura'],
            ['name' => 'Welikanda'],
            ['name' => 'Aralaganwila'],
            ['name' => 'Hingurakgoda'],
            ['name' => 'Medirigiriya'],
            ['name' => 'Habarana'],
            ['name' => 'Bakamuna'],
            ['name' => 'Minneriya'],

            // Uva Province
            // Badulla
            ['name' => 'Badulla'],
            ['name' => 'Passara'],
            ['name' => 'Madolseema'],
            ['name' => 'Lunugala'],
            ['name' => 'Mahiyangane'],
            ['name' => 'Giradurukotte'],
            ['name' => 'Kandaketiya'],
            ['name' => 'Haliela'],
            ['name' => 'Redeemaliyadda / (Kanugolla)'],
            ['name' => 'Bandarawela'],
            ['name' => 'Ella'],
            ['name' => 'Welimada'],
            ['name' => 'Uvaparanagama'],
            ['name' => 'Etempitiya'],
            ['name' => 'Haputale'],
            ['name' => 'Diyathalawa'],
            ['name' => 'Koslanda'],
            ['name' => 'Bogahakumbura'],

            // Monaragala
            ['name' => 'Monaragala'],
            ['name' => 'Siyambalanduwa'],
            ['name' => 'Dambagalla'],
            ['name' => 'Athimale'],
            ['name' => 'Bibila'],
            ['name' => 'Medagama'],
            ['name' => 'Buttala'],
            ['name' => 'Badalkumbura'],
            ['name' => 'Gonaganara'],
            ['name' => 'wellawaya'],
            ['name' => 'Thanamalwila'],
            ['name' => 'Hambegamuwa'],
            ['name' => 'Mahakalugolla'],
            ['name' => 'Kudaoya'],
            ['name' => 'Okkampitiya'],
            ['name' => 'Karandugala'],
            ['name' => '14 Miles (Govindapura)'],

            // Sabaragamuwa Province
            // Ratnapura
            ['name' => 'Ratnapura'],
            ['name' => 'Wewalwatta'],
            ['name' => 'Balangoda'],
            ['name' => 'Opanayaka'],
            ['name' => 'Kaltota'],
            ['name' => 'Weligepola'],
            ['name' => 'Kahawatta'],
            ['name' => 'Rakwana'],
            ['name' => 'Ayagama'],
            ['name' => 'Kalawana'],
            ['name' => 'Nivithigala'],
            ['name' => 'Kuruwita'],
            ['name' => 'Ehaliyagoda'],
            ['name' => 'Kiriella'],
            ['name' => 'Pinnawala'],
            ['name' => 'Siripagama'],
            ['name' => 'Pelmadulla'],
            ['name' => 'Godakawela'],
            ['name' => 'Udawalawa'],
            ['name' => 'Kolonna'],
            ['name' => 'Panamure'],
            ['name' => 'Embilipitiya'],
            ['name' => 'Kuttigala'],
            ['name' => 'Sewanagala'],

            // Kegalle
            ['name' => 'Kegalle'],
            ['name' => 'Wrakapola'],
            ['name' => 'Aranayaka'],
            ['name' => 'Dedigama'],
            ['name' => 'Mawanella'],
            ['name' => 'Rambukkana'],
            ['name' => 'Pindeniya'],
            ['name' => 'Hemmathagama'],
            ['name' => 'Awissawella'],
            ['name' => 'Kosgama'],
            ['name' => 'Deraniyagala'],
            ['name' => 'Ruwanwella'],
            ['name' => 'Yatiyantota'],
            ['name' => 'Kithulgala'],
            ['name' => 'Bulathkohupitiya'],

         ];

        DB::table('police_stations')->insertOrIgnore($police);

    }
}
